# Generated by Django 3.1.4 on 2020-12-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homeworks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="deadline",
            field=models.IntegerField(default=7),
        ),
    ]
