# Generated by Django 3.1.4 on 2020-12-31 16:03

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homeworks", "0002_homework_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homework",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2020, 12, 31, 19, 3, 33, 404519)
            ),
        ),
        migrations.AlterField(
            model_name="homeworkresult",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2020, 12, 31, 19, 3, 33, 405518)
            ),
        ),
    ]
