# Generated by Django 3.1.4 on 2020-12-31 16:19

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homeworks", "0003_auto_20201231_1903"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homework",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2020, 12, 31, 19, 19, 56, 402582)
            ),
        ),
        migrations.AlterField(
            model_name="homeworkresult",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2020, 12, 31, 19, 19, 56, 403581)
            ),
        ),
    ]
